import { STTModelMetadata } from '../types/voice';

/**
 * Centralized Speech-To-Text (STT) Registry for all 22 Official Scheduled Indian Languages + English.
 * 
 * Defines Online Recognition provider capabilities and AI4Bharat IndicConformer / Sherpa-ONNX
 * on-device ASR models for true local inference without cloud dependencies.
 */
export const STT_MODEL_REGISTRY: Record<string, STTModelMetadata> = {
  te: {
    languageId: 'te',
    displayName: 'Telugu',
    sttLocale: 'te-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-te-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '38 MB',
    isLocalInstalled: true,
    notes: 'Verified proof-of-concept local Indic ASR engine + online streaming STT.',
  },
  hi: {
    languageId: 'hi',
    displayName: 'Hindi',
    sttLocale: 'hi-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-hi-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '39 MB',
    isLocalInstalled: true,
    notes: 'Native offline recognition model installed on device + online STT.',
  },
  ta: {
    languageId: 'ta',
    displayName: 'Tamil',
    sttLocale: 'ta-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-ta-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '38 MB',
    isLocalInstalled: true,
  },
  bn: {
    languageId: 'bn',
    displayName: 'Bengali',
    sttLocale: 'bn-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-bn-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: true,
  },
  kn: {
    languageId: 'kn',
    displayName: 'Kannada',
    sttLocale: 'kn-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-kn-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '38 MB',
    isLocalInstalled: true,
  },
  mr: {
    languageId: 'mr',
    displayName: 'Marathi',
    sttLocale: 'mr-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-mr-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: true,
  },
  ml: {
    languageId: 'ml',
    displayName: 'Malayalam',
    sttLocale: 'ml-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-ml-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '39 MB',
    isLocalInstalled: true,
  },
  gu: {
    languageId: 'gu',
    displayName: 'Gujarati',
    sttLocale: 'gu-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-gu-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '36 MB',
    isLocalInstalled: true,
  },
  pa: {
    languageId: 'pa',
    displayName: 'Punjabi',
    sttLocale: 'pa-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-pa-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '36 MB',
    isLocalInstalled: true,
  },
  ur: {
    languageId: 'ur',
    displayName: 'Urdu',
    sttLocale: 'ur-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-ur-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: true,
  },
  or: {
    languageId: 'or',
    displayName: 'Odia',
    sttLocale: 'or-IN',
    onlineSupported: true,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-or-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '38 MB',
    isLocalInstalled: false,
    notes: 'Online supported; offline requires one-time ASR model download.',
  },
  as: {
    languageId: 'as',
    displayName: 'Assamese',
    sttLocale: 'as-IN',
    onlineSupported: true,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-as-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '36 MB',
    isLocalInstalled: false,
    notes: 'Online supported; offline requires one-time ASR model download.',
  },
  ne: {
    languageId: 'ne',
    displayName: 'Nepali',
    sttLocale: 'ne-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'AI4Bharat IndicConformer / Platform SpeechRecognizer',
    modelName: 'indicconformer-ne-v1',
    engine: 'AI4Bharat IndicConformer / Sherpa-ONNX',
    license: 'MIT / CC-BY-4.0',
    approxSize: '36 MB',
    isLocalInstalled: true,
  },
  sa: {
    languageId: 'sa',
    displayName: 'Sanskrit',
    sttLocale: 'sa-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-sa-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '39 MB',
    isLocalInstalled: false,
    notes: 'Requires downloadable local IndicConformer model package.',
  },
  kok: {
    languageId: 'kok',
    displayName: 'Konkani',
    sttLocale: 'kok-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-kok-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: false,
  },
  mai: {
    languageId: 'mai',
    displayName: 'Maithili',
    sttLocale: 'mai-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-mai-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: false,
  },
  doi: {
    languageId: 'doi',
    displayName: 'Dogri',
    sttLocale: 'doi-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-doi-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '36 MB',
    isLocalInstalled: false,
  },
  brx: {
    languageId: 'brx',
    displayName: 'Bodo',
    sttLocale: 'brx-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-brx-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '36 MB',
    isLocalInstalled: false,
  },
  ks: {
    languageId: 'ks',
    displayName: 'Kashmiri',
    sttLocale: 'ks-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-ks-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '38 MB',
    isLocalInstalled: false,
  },
  mni: {
    languageId: 'mni',
    displayName: 'Manipuri',
    sttLocale: 'mni-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-mni-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: false,
  },
  sat: {
    languageId: 'sat',
    displayName: 'Santali',
    sttLocale: 'sat-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-sat-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '37 MB',
    isLocalInstalled: false,
  },
  sd: {
    languageId: 'sd',
    displayName: 'Sindhi',
    sttLocale: 'sd-IN',
    onlineSupported: false,
    offlineSupported: false,
    provider: 'AI4Bharat IndicConformer ASR',
    modelName: 'indicconformer-sd-v1',
    engine: 'AI4Bharat IndicConformer',
    license: 'MIT / CC-BY-4.0',
    approxSize: '38 MB',
    isLocalInstalled: false,
  },
  en: {
    languageId: 'en',
    displayName: 'English',
    sttLocale: 'en-IN',
    onlineSupported: true,
    offlineSupported: true,
    provider: 'Native SpeechRecognizer / Sherpa-ONNX',
    modelName: 'sherpa-onnx-en-v1',
    engine: 'Native / Sherpa-ONNX',
    license: 'Apache-2.0',
    approxSize: '32 MB',
    isLocalInstalled: true,
  },
};

export function getSTTModelMetadata(languageIdentifier?: string | null): STTModelMetadata | undefined {
  if (!languageIdentifier) return STTMODEL_LOOKUP('en');
  const norm = languageIdentifier.toLowerCase().split('-')[0];
  return STTMODEL_LOOKUP(norm);
}

function STTMODEL_LOOKUP(key: string): STTModelMetadata | undefined {
  return STT_MODEL_REGISTRY[key] || STT_MODEL_REGISTRY['en'];
}
