import { TTSModelMetadata } from '../types/voice';

/**
 * Centralized On-Device TTS Model Registry for all 22 Official Scheduled Indian Languages + English.
 * 
 * Provides metadata, local model capability, licensing, and offline storage strategy.
 * Zero cloud dependency — all models are designed for local CPU on-device inference.
 */
export const LOCAL_TTS_MODEL_REGISTRY: Record<string, TTSModelMetadata> = {
  te: {
    languageId: 'te',
    displayName: 'Telugu',
    modelName: 'vits-indic-te-telugu-v1',
    engine: 'Sherpa-ONNX / Indic-VITS',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.4 MB',
    status: 'LOCAL_MODEL_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
    notes: 'Verified proof-of-concept on-device local Indic TTS model.',
  },
  hi: {
    languageId: 'hi',
    displayName: 'Hindi',
    modelName: 'vits-indic-hi-hindi-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '22.1 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
    notes: 'Native device offline voice pre-installed + Indic ONNX compatible.',
  },
  ta: {
    languageId: 'ta',
    displayName: 'Tamil',
    modelName: 'vits-indic-ta-tamil-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '20.8 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
    notes: 'Native device offline voice pre-installed + Indic ONNX compatible.',
  },
  bn: {
    languageId: 'bn',
    displayName: 'Bengali',
    modelName: 'vits-indic-bn-bengali-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.9 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  mr: {
    languageId: 'mr',
    displayName: 'Marathi',
    modelName: 'vits-indic-mr-marathi-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.0 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  kn: {
    languageId: 'kn',
    displayName: 'Kannada',
    modelName: 'vits-indic-kn-kannada-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '22.5 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  ml: {
    languageId: 'ml',
    displayName: 'Malayalam',
    modelName: 'vits-indic-ml-malayalam-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '23.0 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  gu: {
    languageId: 'gu',
    displayName: 'Gujarati',
    modelName: 'vits-indic-gu-gujarati-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.2 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  pa: {
    languageId: 'pa',
    displayName: 'Punjabi',
    modelName: 'vits-indic-pa-punjabi-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '20.5 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  or: {
    languageId: 'or',
    displayName: 'Odia',
    modelName: 'vits-indic-or-odia-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '22.0 MB',
    status: 'AVAILABLE_BUT_OFFLINE_UNKNOWN',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
    notes: 'Requires one-time voice model download for offline usage.',
  },
  as: {
    languageId: 'as',
    displayName: 'Assamese',
    modelName: 'vits-indic-as-assamese-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.5 MB',
    status: 'AVAILABLE_BUT_OFFLINE_UNKNOWN',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
    notes: 'Requires one-time voice model download for offline usage.',
  },
  ur: {
    languageId: 'ur',
    displayName: 'Urdu',
    modelName: 'vits-indic-ur-urdu-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.8 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  ne: {
    languageId: 'ne',
    displayName: 'Nepali',
    modelName: 'vits-indic-ne-nepali-v1',
    engine: 'Sherpa-ONNX / Native System',
    license: 'Apache-2.0 / MIT',
    approxSize: '20.9 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
  sa: {
    languageId: 'sa',
    displayName: 'Sanskrit',
    modelName: 'vits-indic-sa-sanskrit-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '22.4 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
    notes: 'Classical Indic model available via one-time package download.',
  },
  kok: {
    languageId: 'kok',
    displayName: 'Konkani',
    modelName: 'vits-indic-kok-konkani-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.0 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  mai: {
    languageId: 'mai',
    displayName: 'Maithili',
    modelName: 'vits-indic-mai-maithili-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.2 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  doi: {
    languageId: 'doi',
    displayName: 'Dogri',
    modelName: 'vits-indic-doi-dogri-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.0 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  brx: {
    languageId: 'brx',
    displayName: 'Bodo',
    modelName: 'vits-indic-brx-bodo-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '20.6 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  ks: {
    languageId: 'ks',
    displayName: 'Kashmiri',
    modelName: 'vits-indic-ks-kashmiri-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.8 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  mni: {
    languageId: 'mni',
    displayName: 'Manipuri',
    modelName: 'vits-indic-mni-manipuri-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '20.7 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  sat: {
    languageId: 'sat',
    displayName: 'Santali',
    modelName: 'vits-indic-sat-santali-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.0 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  sd: {
    languageId: 'sd',
    displayName: 'Sindhi',
    modelName: 'vits-indic-sd-sindhi-v1',
    engine: 'Sherpa-ONNX / Piper',
    license: 'Apache-2.0 / MIT',
    approxSize: '21.4 MB',
    status: 'UNAVAILABLE',
    offlineStatus: 'ONE_TIME_DOWNLOAD',
    isLocalInstalled: false,
  },
  en: {
    languageId: 'en',
    displayName: 'English',
    modelName: 'vits-indic-en-india-v1',
    engine: 'Native System / Sherpa-ONNX',
    license: 'Apache-2.0 / MIT',
    approxSize: '19.5 MB',
    status: 'NATIVE_OFFLINE_AVAILABLE',
    offlineStatus: 'BUNDLED_OFFLINE',
    isLocalInstalled: true,
  },
};

/**
 * Lookup TTS model metadata by language id (e.g. 'te', 'hi', 'en') or locale ('te-IN').
 */
export function getTTSModelMetadata(languageIdentifier?: string | null): TTSModelMetadata | undefined {
  if (!languageIdentifier) return LOCAL_TTS_MODEL_REGISTRY['en'];
  const norm = languageIdentifier.toLowerCase().split('-')[0];
  return LOCAL_TTS_MODEL_REGISTRY[norm];
}
