/**
 * Organized dictionaries for synonyms, contractions, and common misspellings.
 */

export const CONTRACTIONS: Record<string, string> = {
  "i'm": "i am",
  "what's": "what is",
  "who's": "who is",
  "where's": "where is",
  "when's": "when is",
  "how's": "how is",
  "let's": "let us",
  "can't": "cannot",
  "cant": "cannot",
  "don't": "do not",
  "dont": "do not",
  "it's": "it is",
  "you're": "you are",
  "that's": "that is",
  "there's": "there is",
  "didn't": "did not",
  "doesn't": "does not",
  "haven't": "have not",
  "hasn't": "has not",
  "wouldn't": "would not",
  "shouldn't": "should not",
  "couldn't": "could not",
};

export const COMMON_TYPOS: Record<string, string> = {
  whn: 'when',
  wen: 'when',
  wht: 'what',
  wat: 'what',
  medicne: 'medicine',
  medcine: 'medicine',
  medisin: 'medicine',
  medecine: 'medicine',
  meds: 'medicine',
  tablt: 'tablet',
  tablett: 'tablet',
  tbalet: 'tablet',
  pilll: 'pill',
  pils: 'pill',
  cargiver: 'caregiver',
  caregivver: 'caregiver',
  carer: 'caregiver',
  caregir: 'caregiver',
  remeber: 'remember',
  remembr: 'remember',
  rmember: 'remember',
  remindr: 'reminder',
  remider: 'reminder',
  remidner: 'reminder',
  scard: 'scared',
  scarred: 'scared',
  afrad: 'afraid',
  frightend: 'frightened',
  morng: 'morning',
  mornin: 'morning',
  mornig: 'morning',
  tday: 'today',
  toda: 'today',
  tomorow: 'tomorrow',
  tomorw: 'tomorrow',
  confsed: 'confused',
  cnfsd: 'confused',
  hlp: 'help',
  plz: 'please',
  pls: 'please',
  thx: 'thank you',
  thanx: 'thank you',
  ty: 'thank you',
};

export const SYNONYM_GROUPS = {
  MEDICINE: [
    'medicine',
    'medicines',
    'medication',
    'medications',
    'tablet',
    'tablets',
    'pill',
    'pills',
    'dose',
    'dosage',
    'doses',
    'drug',
    'drugs',
    'capsule',
    'capsules',
    'syrup',
    'injection',
    'prescription',
  ],

  CAREGIVER: [
    'caregiver',
    'caregivers',
    'carer',
    'carers',
    'nurse',
    'nurses',
    'helper',
    'helpers',
    'guardian',
    'attendant',
    'caretaker',
  ],

  IDENTITY: [
    'who am i',
    'my name',
    'what is my name',
    'tell me my name',
    'know who i am',
    'my identity',
  ],

  LOCATION: [
    'where am i',
    'where are we',
    'what place is this',
    'which place is this',
    'what is this place',
    'am i home',
    'am i at home',
    'am i in hospital',
    'my location',
    'where i am',
  ],

  TIME_QUERY: [
    'when',
    'what time',
    'at what time',
    'which time',
    'when is',
    'when do',
    'when should',
    'timing',
    'schedule',
    'scheduled for',
  ],

  WHAT_QUERY: [
    'what',
    'what is',
    'which',
    'which one',
    'what is it',
    'tell me what',
    'what are',
  ],

  GAME: [
    'game',
    'games',
    'play',
    'playing',
    'match pair',
    'memory game',
    'puzzle',
    'fun game',
  ],

  ACTIVITY: [
    'activity',
    'activities',
    'walk',
    'music',
    'exercise',
    'something to do',
    'things to do',
    'what can i do',
    'bored',
    'boring',
  ],

  REMINDER: [
    'reminder',
    'reminders',
    'upcoming reminder',
    'next reminder',
    'alert',
    'alerts',
    'what should i do next',
    'what is next',
  ],

  FEAR_EMOTION: [
    'scared',
    'afraid',
    'frightened',
    'terrified',
    'fear',
    'anxious',
    'panic',
    'worried',
    'nervous',
    'shaking',
  ],

  CONFUSION_EMOTION: [
    'confused',
    'lost',
    'disoriented',
    'do not understand',
    'cannot understand',
    'what is happening',
    'do not know where',
  ],

  MEMORY_LOSS: [
    'cannot remember',
    'can not remember',
    'cant remember',
    'forgot',
    'forgotten',
    'do not remember',
    'dont remember',
    'lost my memory',
    'cannot recall',
  ],

  LONELINESS: [
    'alone',
    'nobody is here',
    'no one is here',
    'lonely',
    'where is everyone',
    'where is everybody',
    'all by myself',
  ],

  HELP_REQUEST: [
    'help',
    'help me',
    'need help',
    'please help',
    'emergency',
    'assist me',
    'need assistance',
    'call someone',
  ],
};
