/**
 * Central dictionary for STT fillers, contractions, typos, and semantic phrase groups.
 */

export const STT_FILLERS = [
  /^(uh|um|er|ah|okay|so)\b/gi,
  /^(could\s+you\s+(tell|remind)\s+me|do\s+you\s+know|i\s+want\s+to\s+know|please\s+remind\s+me|i\s+would\s+like\s+to\s+know)\b/gi,
  /^(i\s+do\s+not\s+remember|i\s+dont\s+remember|remind\s+me\s+of)\b/gi,
];

export const CONTRACTIONS: Record<string, string> = {
  "today's": "today",
  "todays": "today",
  "i'm": "i am",
  "what's": "what is",
  "who's": "who is",
  "where's": "where is",
  "when's": "when is",
  "how's": "how is",
  "why's": "why is",
  "let's": "let us",
  "can't": "cannot",
  "cant": "cannot",
  "don't": "do not",
  "dont": "do not",
  "it's": "it is",
  "you're": "you are",
  "that's": "that is",
  "there's": "there is",
  "didn't": "did not",
  "doesn't": "does not",
  "haven't": "have not",
  "hasn't": "has not",
  "wouldn't": "would not",
  "shouldn't": "should not",
  "couldn't": "could not",
  "isn't": "is not",
  "aren't": "are not",
  "wasn't": "was not",
  "weren't": "were not",
};

export const COMMON_TYPOS: Record<string, string> = {
  whn: 'when',
  wen: 'when',
  wht: 'what',
  wat: 'what',
  whr: 'where',
  wer: 'where',
  whoe: 'who',
  hoo: 'who',
  medicne: 'medicine',
  medcine: 'medicine',
  medisin: 'medicine',
  medecine: 'medicine',
  meds: 'medicine',
  medcation: 'medication',
  medcaton: 'medication',
  tablt: 'tablet',
  tablett: 'tablet',
  tbalet: 'tablet',
  pilll: 'pill',
  pils: 'pill',
  cargiver: 'caregiver',
  caregivver: 'caregiver',
  caregivr: 'caregiver',
  carer: 'caregiver',
  caregir: 'caregiver',
  doktor: 'doctor',
  doktr: 'doctor',
  remeber: 'remember',
  remembr: 'remember',
  rmember: 'remember',
  remindr: 'reminder',
  remider: 'reminder',
  remidner: 'reminder',
  reminnder: 'reminder',
  scard: 'scared',
  scarred: 'scared',
  afrad: 'afraid',
  frightend: 'frightened',
  morng: 'morning',
  mornin: 'morning',
  mornig: 'morning',
  tday: 'today',
  toda: 'today',
  tomorow: 'tomorrow',
  tomorw: 'tomorrow',
  yestday: 'yesterday',
  confsed: 'confused',
  cnfsd: 'confused',
  hlp: 'help',
  plz: 'please',
  pls: 'please',
  thx: 'thank you',
  thanx: 'thank you',
  ty: 'thank you',
  dementa: 'dementia',
  dimensia: 'dementia',
  tel: 'tell',
  jok: 'joke',
  favrit: 'favorite',
  favourite: 'favorite',
};

export const SYNONYM_GROUPS = {
  SAFETY: [
    'too much medicine',
    'took medicine twice',
    'overdose',
    'fell',
    'fallen',
    'hurt',
    'chest hurts',
    'chest pain',
    'cannot breathe',
    'cant breathe',
    'bleeding',
    'emergency',
  ],

  MEDICINE: [
    'medicine',
    'medicines',
    'medication',
    'medications',
    'tablet',
    'tablets',
    'pill',
    'pills',
    'dose',
    'dosage',
    'doses',
    'drug',
    'drugs',
    'capsule',
    'capsules',
    'syrup',
    'prescription',
    'take my medicine',
    'take my pills',
    'supposed to take',
  ],

  CAREGIVER: [
    'caregiver',
    'caregivers',
    'carer',
    'carers',
    'nurse',
    'nurses',
    'helper',
    'helpers',
    'guardian',
    'attendant',
    'caretaker',
    'person looking after me',
    'person taking care of me',
    'takes care of me',
    'looks after me',
    'who helps me',
    'person helping me',
  ],

  FAMILY: [
    'family',
    'daughter',
    'son',
    'wife',
    'husband',
    'mother',
    'father',
    'brother',
    'sister',
    'grandchild',
    'children',
    'relative',
  ],

  PATIENT: [
    'my name',
    'who am i',
    'what am i called',
    'what do people call me',
    'my identity',
    'myself',
    'me',
    'who i am',
    'forgot my name',
  ],

  LOCATION: [
    'where',
    'place',
    'location',
    'here',
    'there',
    'home',
    'hospital',
    'room',
    'house',
    'bedroom',
  ],

  REMINDER: [
    'reminder',
    'reminders',
    'remind me',
    'what next',
    'what comes next',
    'what do i do next',
    'what should i do',
    'what am i supposed to do',
    'what is scheduled',
    'schedule',
    'appointment',
    'upcoming',
    'alert',
    'task',
  ],

  TIME: [
    'when',
    'what time',
    'at what time',
    'hour',
    'clock',
    'time',
    'timing',
    'schedule',
  ],

  DATE: [
    'today',
    'tomorrow',
    'yesterday',
    'day',
    'date',
    'which day',
    'what day',
    'date today',
  ],

  ROUTINE: [
    'routine',
    'plan',
    'schedule',
    'doing today',
    'day plan',
    'things to do',
  ],

  GAME: [
    'game',
    'games',
    'play',
    'playing',
    'puzzle',
    'memory match',
    'cognitive game',
    'something fun',
  ],

  ACTIVITY: [
    'activity',
    'activities',
    'walk',
    'music',
    'exercise',
    'something to do',
    'things to do',
    'bored',
    'boring',
    'entertain me',
  ],

  MEMORY: [
    'remember',
    'memory',
    'memories',
    'forgot',
    'tell me about myself',
    'tell me something you remember',
    'what do you remember about me',
    'do you remember me',
    'what do you know about me',
  ],

  HELP: [
    'help',
    'help me',
    'need help',
    'please help',
    'can someone help me',
    'i need someone',
    'emergency help',
    'assist me',
  ],

  EMOTION: [
    'lonely',
    'alone',
    'sad',
    'upset',
    'scared',
    'afraid',
    'worried',
    'bored',
    'unhappy',
    'confused',
    'frightened',
    'terrified',
    'do not know what to do',
  ],

  FOOD: [
    'food',
    'eat',
    'eating',
    'breakfast',
    'lunch',
    'dinner',
    'tea',
    'snack',
    'water',
    'drink',
    'hydration',
  ],

  SLEEP: [
    'sleep',
    'sleeping',
    'bed',
    'bedtime',
    'rest',
    'resting',
    'good night',
    'tired',
  ],

  WEATHER: [
    'weather',
    'rain',
    'sunny',
    'hot',
    'cold',
    'outside',
  ],

  GENERAL_CONVERSATION: [
    'thank you',
    'thanks',
    'hello',
    'hi',
    'good morning',
    'good night',
    'okay',
    'alright',
    'yes',
    'no',
  ],

  APPOINTMENT: [
    'appointment',
    'appointments',
    'doctor appointment',
    'clinic',
    'hospital visit',
    'see the doctor',
  ],

  PREFERENCE: [
    'favorite',
    'favourite',
    'like',
    'enjoy',
    'prefer',
    'hobby',
    'hobbies',
    'favorite food',
    'favorite activity',
    'favorite music',
    'favorite song',
    'favorite color',
  ],

  FAQ: [
    'what is dementia',
    'what is a memory',
    'why do i need reminders',
    'how can i relax',
    'what if i am worried',
    'tell me a joke',
    'tell me a story',
  ],
};
